name: fern
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tqdm
  - regex
  - polars
  - datasets
  - accelerate
  - transformers
  - ipykernel
  - pip
  - setuptools<70
  - ipywidgets
  - pip:
    - torchtune
